version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    executor: node/default
    environment:
      NODE_ENV: ci
      JWT_SECRET: ci_jwt_secret
      SERVER_URL: http://localhost:8080
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: NODE_ENV=ci npm test
          name: Run tests
      - run:
          name: Run posttest cleanup
          command: NODE_ENV=ci npm run posttest

workflows:
  build_test_deploy:
    jobs:
      - build_and_test

