version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    executor: node/default
    environment:
      NODE_ENV: ci
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests

workflows:
  build_test_deploy:
    jobs:
      - build_and_test

