version: 2.1
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - run:
          command: npm build
          name: Build app

workflows:
  build_test_deploy:
    jobs:
      - build_and_test

