version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    executor: node/default
    environment:
      NODE_ENV: ci
      JWT_SECRET: ci_jwt_secret
      SERVER_URL: http://localhost:8080
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Wait for Application to be Ready
          command: |
            # Wait until the application is available
            timeout 60s bash -c 'until curl -s $SERVER_URL; do sleep 1; done'
      - run:
          command: npm test
          name: Run tests

workflows:
  build_test_deploy:
    jobs:
      - build_and_test

